apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comment-sqlite-pvc
  namespace: bluinsights
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-shared

