@Library('ci') _

pipeline {
    agent any
    environment {
        IMAGE_NAME = "bludivehub/bluinsights-blog-service"
        IMAGE_TAG = "${IMAGE_NAME}:${env.BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = 'dockerhub-credentials'
        NAMESPACE = 'bluinsights'
    }
    stages {
        stage('Build & Scan Docker') {
            steps {
                script {
                    docker.buildAndScan('blog-service', './backend/blog-service', IMAGE_TAG)
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.pushImage(IMAGE_TAG, REGISTRY_CREDENTIALS)
                }
            }
        }
        stage('Deploy via Helm') {
            steps {
                script {
                    helm.deployHelmChart('blog-service', '../../helm-charts/blog-service', NAMESPACE, [
                        'image.tag': env.BUILD_NUMBER
                    ])
                }
            }
        }
    }
}

