apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-service.fullname" . }}
spec:
  selector:
    app: {{ include "frontend-service.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80

