apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog-service.fullname" . }}
  labels:
    app: {{ include "blog-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "blog-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "blog-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: images
              mountPath: {{ .Values.persistence.images.mountPath }}
            - name: database
              mountPath: {{ .Values.persistence.database.mountPath }}
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.images.existingClaim }}
        - name: database
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.database.existingClaim }}
 
