@Library('ci') _

pipeline {
    agent any
    stages {
        stage('Trigger Child Pipelines') {
            parallel {
                stage('Blog Service') {
                    steps {
                        build job: 'blog-test', wait: true
                    }
                }
                stage('Comment Service') {
                    steps {
                        build job: 'comment-test', wait: true
                    }
                }
                stage('Frontend Service') {
                    steps {
                        build job: 'frontend-test', wait: true
                    }
                }
            }
        }
    }
}

