@Library('ci') _

pipeline {
    agent any
    stages {
        stage('Trigger Child Pipelines') {
            parallel {
                stage('Blog Service') {
                    steps {
                        build job: 'Blog-Service-CI', wait: true
                    }
                }
                stage('Comment Service') {
                    steps {
                        build job: 'Comment-Service-CI', wait: true
                    }
                }
                stage('Frontend Service') {
                    steps {
                        build job: 'Frontend-Service-CI', wait: true
                    }
                }
            }
        }
    }
}

